// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CommentdropdownController from "./commentdropdown_controller"
application.register("commentdropdown", CommentdropdownController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NavbardropdownController from "./navbardropdown_controller"
application.register("navbardropdown", NavbardropdownController)
